package com.antopina.schedulingappointmentplanner.utils;

public class AppConstants {
    public static final String PRIVACY_POLICY_CONTENT = "Privacy Policy\n" +
            "Last updated: December 05, 2024\n\n" +
            "This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\n" +
            "We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.\n\n" +
            "Interpretation and Definitions\n\n" +
            "1. **Interpretation**\n" +
            "\t- The words of which the initial letter is capitalized have meanings defined under the following conditions.\n" +
            "\t- The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.\n\n" +
            "2. **Definitions**\n" +
            "\tFor the purposes of this Privacy Policy:\n" +
            "\t- **Account**: A unique account created for You to access our Service or parts of our Service.\n" +
            "\t- **Affiliate**: An entity that controls, is controlled by, or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.\n" +
            "\t- **Application**: Refers to ScheDue, the software program provided by the Company.\n" +
            "\t- **Company** (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement): Refers to ScheDue.\n" +
            "\t- **Country**: Refers to the Philippines.\n" +
            "\t- **Device**: Any device that can access the Service such as a computer, a cellphone, or a digital tablet.\n" +
            "\t- **Personal Data**: Any information that relates to an identified or identifiable individual.\n" +
            "\t- **Service**: Refers to the Application.\n" +
            "\t- **Service Provider**: Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, perform services related to the Service, or assist the Company in analyzing how the Service is used.\n" +
            "\t- **Usage Data**: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).\n" +
            "\t- **You**: The individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.\n\n" +
            "Collecting and Using Your Personal Data\n\n" +
            "1. **Types of Data Collected**\n" +
            "\t- **Personal Data**:\n" +
            "\t\tWhile using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n" +
            "\t\t\t- Email address\n" +
            "\t\t\t- First name and last name\n" +
            "\t\t\t- Usage Data\n" +
            "\n\t- **Usage Data**:\n" +
            "\t\tUsage Data is collected automatically when using the Service. Usage Data may include information such as:\n" +
            "\t\t\t- Your Device's Internet Protocol address (e.g., IP address)\n" +
            "\t\t\t- Browser type and version\n" +
            "\t\t\t- The pages of our Service that You visit\n" +
            "\t\t\t- Time and date of Your visit\n" +
            "\t\t\t- Time spent on those pages\n" +
            "\t\t\t- Unique device identifiers and other diagnostic data\n" +
            "\n" +
            "2. **Use of Your Personal Data**\n" +
            "\tThe Company may use Personal Data for the following purposes:\n" +
            "\t- To provide and maintain our Service, including monitoring usage.\n" +
            "\t- To manage Your Account.\n" +
            "\t- For the performance of a contract.\n" +
            "\t- To contact You via email, phone, SMS, or push notifications.\n" +
            "\t- To provide You with news, special offers, and general information about similar services.\n" +
            "\t- To manage Your requests.\n" +
            "\t- For business transfers, mergers, or acquisitions.\n" +
            "\t- For other purposes like data analysis, identifying trends, and improving the Service.\n\n" +
            "3. **Sharing Your Personal Information**\n" +
            "\tWe may share Your information in the following cases:\n" +
            "\t- With Service Providers.\n" +
            "\t- For business transfers.\n" +
            "\t- With affiliates and business partners.\n" +
            "\t- With other users when interacting in public areas.\n" +
            "\t- With Your consent.\n\n" +
            "Security of Your Personal Data\n" +
            "We strive to use commercially acceptable means to protect Your Personal Data but cannot guarantee absolute security.\n\n" +
            "Children's Privacy\n" +
            "Our Service does not address anyone under 13, and we do not knowingly collect data from children under 13.\n\n" +
            "Contact Us\n" +
            "If you have any questions, please email us at: junie.antopina07@gmail.com";


    public static final String TERMS_CONDITIONS_CONTENT = "Welcome to ScheDue! By using our app, you agree to the following terms:\n" +
            "\n" +
            "1. Use of Service:\n" +
            "   - ScheDue is designed to assist with task scheduling and reminders. Users must provide accurate information for reliable functionality.\n" +
            "\n" +
            "2. User Responsibilities:\n" +
            "   - You are responsible for maintaining the confidentiality of your account credentials.\n" +
            "   - Misuse of the platform, including harmful content or illegal activities, is prohibited.\n" +
            "\n" +
            "3. App Updates:\n" +
            "   - Features may be updated or removed at any time to enhance functionality.\n" +
            "\n" +
            "4. Liability:\n" +
            "   - ScheDue is not liable for missed appointments due to technical or user errors.\n" +
            "\n" +
            "By using ScheDue, you accept these terms. For more details, email support@schedueteam.com.\n";

    public static final String ABOUT_CONTENT = "ScheDue is your ultimate scheduling planner and task reminder app, designed to keep your life organized and stress-free. \n" +
            "\n" +
            "Features:\n" +
            "- Create and manage tasks and reminders.\n" +
            "- Customize schedules and notifications.\n" +
            "- Sync data securely across devices.\n" +
            "\n" +
            "Developed with a passion for productivity, ScheDue is here to help you make the most of your time.\n" +
            "\n" +
            "Contact us: support@schedueteam.com\n";
}
